const models = [
  {
    id: 1,
    title: "3D Model of Miniature Bedroom Scene",
    description:
      "3D model of a miniature isometric bedroom with furniture like bed, bedside tables, desk and decor.",
    category: "Scenes",
    src: "statics/textured_meshes/case1.glb",
    thumbnail: "statics/textured_meshes/case1.png",
    referenceImage: "statics/textured_meshes/case1.png",
    polygons: "10,000",
    textures: "1K PBR",
    materials: "3",
    textured: false,
  },
  {
    id: 2,
    title: "3D Model of Miniature Bedroom Scene",
    description:
      "3D model of a miniature isometric bedroom with furniture like bed, bedside tables, desk and decor.",
    category: "Scenes",
    src: "statics/textured_meshes/case2.glb",
    thumbnail: "statics/textured_meshes/case2.png",
    referenceImage: "statics/textured_meshes/case2.png",
    polygons: "10,000",
    textures: "1K PBR",
    materials: "3",
    textured: false,
  },
  {
    id: 3,
    title: "3D Model of Miniature Bedroom Scene",
    description:
      "3D model of a miniature isometric bedroom with furniture like bed, bedside tables, desk and decor.",
    category: "Scenes",
    src: "statics/textured_meshes/case3.glb",
    thumbnail: "statics/textured_meshes/case3.jpg",
    referenceImage: "statics/textured_meshes/case3.jpg",
    polygons: "10,000",
    textures: "1K PBR",
    materials: "3",
    textured: false,
  },
  {
    id: 4,
    title: "3D Model of Miniature Bedroom Scene",
    description:
      "3D model of a miniature isometric bedroom with furniture like bed, bedside tables, desk and decor.",
    category: "Scenes",
    src: "statics/textured_meshes/case4.glb",
    thumbnail: "statics/textured_meshes/case4.png",
    referenceImage: "statics/textured_meshes/case4.png",
    polygons: "10,000",
    textures: "1K PBR",
    materials: "3",
    textured: false,
  },
  {
    id: 5,
    title: "3D Model of Miniature Bedroom Scene",
    description:
      "3D model of a miniature isometric bedroom with furniture like bed, bedside tables, desk and decor.",
    category: "Scenes",
    src: "statics/textured_meshes/case5.glb",
    thumbnail: "statics/textured_meshes/case5.png",
    referenceImage: "statics/textured_meshes/case5.png",
    polygons: "10,000",
    textures: "1K PBR",
    materials: "3",
    textured: false,
  },
  {
    id: 6,
    title: "3D Model of Miniature Bedroom Scene",
    description:
      "3D model of a miniature isometric bedroom with furniture like bed, bedside tables, desk and decor.",
    category: "Scenes",
    src: "statics/textured_meshes/case6.glb",
    thumbnail: "statics/textured_meshes/case6.png",
    referenceImage: "statics/textured_meshes/case6.png",
    polygons: "10,000",
    textures: "1K PBR",
    materials: "3",
    textured: false,
  },
];
